/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.PhatThuongManagerFrame;

import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.MysqlConnection;

/**
 *
 * @author oOOo
 */
public class ThongKeQuaCuoiNam extends javax.swing.JFrame {

    private DefaultTableModel tblModel;
    private DefaultTableModel tblModel1;
    private JFrame parentJFrame;
    private JFrame parentFrame;

    /**
     * Creates new form ThongKeQuaDipDacBiet
     */
    public ThongKeQuaCuoiNam(JFrame parentJFrame) {
        initComponents();
        initTableModel();
        initTableModel1();
        this.parentJFrame = parentJFrame;
        parentJFrame.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parentJFrame.setEnabled(true);
                close();
            }
        });
        showHK();
    }

    private void initTableModel() {
        String[] columnNames = new String[]{"STT", "ID hộ", "Số quà đã nhận", "Tổng giá trị"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
        tblthongke.setModel(tblModel);

        tblthongke.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        tblthongke.setRowHeight(30);
        tblthongke.validate();
        tblthongke.repaint();
        tblthongke.setFont(new Font("Arial", Font.PLAIN, 14));
        tblthongke.getColumnModel().getColumn(0).setMaxWidth(40);
        tblthongke.getColumnModel().getColumn(0).setMinWidth(40);
        tblthongke.getColumnModel().getColumn(0).setPreferredWidth(80);
    }

    private void initTableModel1() {
        String[] columnNames = new String[]{"STT", "ID Hộ Khẩu", "ID nhân khẩu", "Tên nhân khẩu", "Phần quà", "Giá trị"};
        tblModel1 = new DefaultTableModel();
        tblModel1.setColumnIdentifiers(columnNames);
        tblchitiet.setModel(tblModel1);

        tblchitiet.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        tblchitiet.setRowHeight(30);
        tblchitiet.validate();
        tblchitiet.repaint();
        tblchitiet.setFont(new Font("Arial", Font.PLAIN, 12));
        tblchitiet.getColumnModel().getColumn(0).setMaxWidth(40);
        tblchitiet.getColumnModel().getColumn(0).setMinWidth(40);
        tblchitiet.getColumnModel().getColumn(0).setPreferredWidth(80);
    }

    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }

    private void showHK() {
        Connection conn = null;
        Statement stm = null;

        try {
            conn = MysqlConnection.getMysqlConnection();

            String sql = "select idHoKhau, count(IDPhanQua) as sophanthuong, count(IDPhanQua)*10000 as sotienqua "
                    + "from nhan_khau n, thanh_vien_cua_ho t, phat_thuong_cuoi_nam p "
                    + "where t.idNhanKhau = n.id and n.ID = p.IDHS  group by idHoKhau";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblModel.setRowCount(0);
            while (rs.next()) {
                tblModel.addRow(new Object[]{
                    tblModel.getRowCount() + 1,
                    rs.getString("idHoKhau"),
                    rs.getInt("sophanthuong"),
                    rs.getInt("sotienqua"),});
            }
            tblModel.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblthongke = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnchitiet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblchitiet = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Phát thưởng cuối năm");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblthongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "ID hộ", "Tổng số quà đã nhận", "Tổng giá trị"
            }
        ));
        tblthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblthongkeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblthongke);
        if (tblthongke.getColumnModel().getColumnCount() > 0) {
            tblthongke.getColumnModel().getColumn(0).setMinWidth(50);
            tblthongke.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 450, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Bảng thống kê số phần quà đã phát thưởng cuối năm");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 400, 25));

        btnchitiet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnchitiet.setText("Thống Kê Chi Tiết");
        btnchitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchitietActionPerformed(evt);
            }
        });
        getContentPane().add(btnchitiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 140, -1));

        tblchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID Hộ Khẩu", "ID nhân khẩu", "Họ Tên", "Phần quà", "Giá trị"
            }
        ));
        jScrollPane2.setViewportView(tblchitiet);
        if (tblchitiet.getColumnModel().getColumnCount() > 0) {
            tblchitiet.getColumnModel().getColumn(0).setMinWidth(50);
            tblchitiet.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 600, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID hộ khẩu cần thống kê:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 30));

        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 200, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Thống kê chi tiết từng hộ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 310, -1));

        jLabel4.setText("(Nhập hoặc chọn ở bảng phía trên)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 220, -1));

        jLabel5.setText("  ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchitietActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Statement stm = null;

        try {
            conn = MysqlConnection.getMysqlConnection();
            if (txtTimkiem.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ban chua nhap gia tri tim kiem");
            } else {
                String sql1 = "select DISTINCT t.idHoKhau, dh.IDNhanKhau, dh.hoTen, pt.tenQua, pt.giaTri " +
                                "from thanh_vien_cua_ho t, nhan_khau n, phat_thuong_cuoi_nam p, phan_qua pt, danh_hieu dh " +
                                "where p.IDHS = dh.ID and p.IDPhanQua = pt.ID and dh.IDNhanKhau = n.ID "
                                + "and idHoKhau = " + txtTimkiem.getText() + "";

                PreparedStatement pstmt = conn.prepareStatement(sql1);

                ResultSet rs1 = pstmt.executeQuery();

                tblModel1.setRowCount(0);
                while (rs1.next()) {
                    tblModel1.addRow(new Object[]{
                        tblModel1.getRowCount() + 1,
                        rs1.getInt("idHoKhau"),
                        rs1.getInt("IDNhanKhau"),
                        rs1.getString("hoTen"),
                        rs1.getString("tenQua"),
                        rs1.getInt("giaTri"),});
                }

                tblModel1.fireTableDataChanged();
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnchitietActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblthongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblthongkeMouseClicked
        // TODO add your handling code here:
        int selectIndex = tblthongke.getSelectedRow();
        if (selectIndex >= 0) {
            String id = String.valueOf(tblthongke.getValueAt(selectIndex, 1));
            txtTimkiem.setText(id);
        }
    }//GEN-LAST:event_tblthongkeMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchitiet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblchitiet;
    private javax.swing.JTable tblthongke;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
