/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import models.HocSinh;
import services.MysqlConnection;
import views.PhatThuongManagerFrame.DipDacBietJFrame;
import views.PhatThuongManagerFrame.PTCuoiNamJFrame;
import views.PhatThuongManagerFrame.PTDacBietJrame;
import views.PhatThuongManagerFrame.QuanLyPhanQuaJFrame;
import views.PhatThuongManagerFrame.ThongKeQuaCuoiNam;
import views.PhatThuongManagerFrame.ThongKeQuaDipDacBiet;


/**
 *
 * @author TNTDT
 */
public class PhatThuongManagePanel extends javax.swing.JPanel {

    private JFrame parentFrame;
    DefaultTableModel tableModel;
    List<HocSinh> lstHs;

    /**
     * Creates new form HoKhauManagePanel
     *
     * @param parentFrame
     */
    public PhatThuongManagePanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
       
    }

    /**
     * Creates new form PhatThuongManagePanel
     */
    public void show() {
        Connection conn = null;
        Statement stm = null;

//        try {
//            conn = MysqlConnection.getMysqlConnection();
//            String sql = "select db.IDHS, db.hoTen, tongQua, tongTien "
//                    + "from pt_dip_dac_biet db, phat_thuong_cuoi_nam cn, danh_hieu dh, phan_qua q "
//                    + "where cn.IDHS = dh.ID and db.IDPhanQua = q.ID and cn.IDPhanQua = q.ID and  db.IDPhanQua = q.ID ";
//            PreparedStatement pstmt = conn.prepareStatement(sql);
//            ResultSet rs = pstmt.executeQuery();
//            tableModel.setRowCount(0);
//            while (rs.next()) {
//                tableModel.addRow(new Object[]{
//                    tableModel.getRowCount() + 1,
//                    rs.getString("ID"),
//                    rs.getInt("hoTen"),
//                    rs.getInt("tongQua"),
//                    rs.getInt("tongTien"),});
//            }
//            tableModel.fireTableDataChanged();
//
//        } catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(PhatThuongManagePanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPhatThuongCuoiNam = new javax.swing.JButton();
        btnphathuongdacbiet = new javax.swing.JButton();
        btnQuanLyPhanQua = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnthongkequa = new javax.swing.JButton();
        btncuoinam = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ CẤP PHÁT PHẦN THƯỞNG");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 6, 335, 30));

        btnPhatThuongCuoiNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPhatThuongCuoiNam.setText("PHÁT THƯỞNG CUỐI NĂM");
        btnPhatThuongCuoiNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhatThuongCuoiNamActionPerformed(evt);
            }
        });
        add(btnPhatThuongCuoiNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 226, 53));

        btnphathuongdacbiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnphathuongdacbiet.setText("Phát Thưởng Dịp Đặc Biệt");
        btnphathuongdacbiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphathuongdacbietActionPerformed(evt);
            }
        });
        add(btnphathuongdacbiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 240, 54));

        btnQuanLyPhanQua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyPhanQua.setText("QUẢN LÝ PHẦN QUÀ");
        btnQuanLyPhanQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyPhanQuaActionPerformed(evt);
            }
        });
        add(btnQuanLyPhanQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 226, 52));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("QL PHÁT QUÀ DỊP ĐẶC BIỆT");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 240, 55));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 6, 103, -1));

        btnthongkequa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnthongkequa.setText("Thống Kê Quà Dịp Đặc Biệt");
        btnthongkequa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkequaActionPerformed(evt);
            }
        });
        add(btnthongkequa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 240, 54));

        btncuoinam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncuoinam.setText("Thống Kê Quà Dịp Cuối Năm");
        btncuoinam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuoinamActionPerformed(evt);
            }
        });
        add(btncuoinam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 54));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPhatThuongCuoiNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhatThuongCuoiNamActionPerformed
        // TODO add your handling code here:
        PTCuoiNamJFrame ptCuoiNam = new PTCuoiNamJFrame(parentFrame);
        ptCuoiNam.setLocationRelativeTo(null);
        ptCuoiNam.setResizable(false);
        ptCuoiNam.setVisible(true);

    }//GEN-LAST:event_btnPhatThuongCuoiNamActionPerformed

    private void btnQuanLyPhanQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyPhanQuaActionPerformed
        // TODO add your handling code here:
        QuanLyPhanQuaJFrame qlPhanQua = new QuanLyPhanQuaJFrame(parentFrame);
        qlPhanQua.setLocationRelativeTo(null);
        qlPhanQua.setResizable(false);
        qlPhanQua.setVisible(true);

    }//GEN-LAST:event_btnQuanLyPhanQuaActionPerformed

    private void btnphathuongdacbietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphathuongdacbietActionPerformed
        // TODO add your handling code here:
        PTDacBietJrame phatThuong = new PTDacBietJrame(parentFrame);
        phatThuong.setLocationRelativeTo(null);
        phatThuong.setResizable(false);
        phatThuong.setVisible(true);
    }//GEN-LAST:event_btnphathuongdacbietActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DipDacBietJFrame dipDB = new DipDacBietJFrame(parentFrame);
        dipDB.setLocationRelativeTo(null);
        dipDB.setResizable(false);
        dipDB.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnthongkequaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkequaActionPerformed
        // TODO add your handling code here:
        ThongKeQuaDipDacBiet thongke = new ThongKeQuaDipDacBiet(parentFrame);
        thongke.setLocationRelativeTo(null);
        thongke.setResizable(false);
        thongke.setVisible(true);
    }//GEN-LAST:event_btnthongkequaActionPerformed

    private void btncuoinamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuoinamActionPerformed
        // TODO add your handling code here:
        ThongKeQuaCuoiNam thongke1 = new ThongKeQuaCuoiNam(parentFrame);
        thongke1.setLocationRelativeTo(null);
        thongke1.setResizable(false);
        thongke1.setVisible(true);
    }//GEN-LAST:event_btncuoinamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhatThuongCuoiNam;
    private javax.swing.JButton btnQuanLyPhanQua;
    private javax.swing.JButton btncuoinam;
    private javax.swing.JButton btnphathuongdacbiet;
    private javax.swing.JButton btnthongkequa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
